name: "Web Deploy - Live"

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RADIUS_HOCKEY }}'
          channelId: live
          projectId: radius-hockey
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks