name: "Web Deploy - Preview"

on:
  pull_request:
    paths:
      - 'web/**'

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./web
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RADIUS_HOCKEY }}'
          projectId: radius-hockey
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
